language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.5
  - DJANGO=1.5.1
  - DJANGO=1.6.2
install:
  - pip install Django==$DJANGO six
  - python setup.py install
script: python setup.py test
notifications:
  email:
    recipients:
      - contact@skwissh.com
    on_success: always
    on_failure: always
